# Generated by Django 2.2.3 on 2019-07-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('joined', models.IntegerField()),
                ('conference', models.CharField(choices=[('Eastern', 'EASTERN'), ('Western', 'WESTERN'), ('Future', 'FUTURE')], default='Eastern', max_length=15)),
            ],
        ),
    ]
